name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 22
          distribution: 'adopt'

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v3.4.2
