name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 22
          distribution: 'adopt'

      - name: Check Java Syntax
        run: find . -name "*.java" -exec javac {} +

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.11'

      - name: Install MySQL server and client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server mysql-client
  
      - name: Start MySQL server
        run: |
          sudo service mysql start
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY 'root';"
          sudo mysql -e "FLUSH PRIVILEGES;"
  
      - name: Create dummy database
        run: |
          mysql -u root -proot -e 'CREATE DATABASE dummy;'
  
      - name: Check SQL syntax
        run: |
          for file in $(find . -name '*.sql'); do
            echo "Checking syntax for $file"
            mysql -u root -proot --database=dummy --force < $file || exit 1
          done
