name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 22
          distribution: 'adopt'

      - name: Check Java Syntax
        run: find . -name "*.java" -exec javac {} +

      # - name: Install MySQL client
      #   run: sudo apt-get install -y mysql-client
  
      # - name: Start MySQL server
      #   run: |
      #     sudo apt-get install -y mysql-server
      #     sudo service mysql start
  
      # - name: Create dummy database
      #   run: |
      #     sudo mysql -e 'CREATE DATABASE dummy;'
  
      # - name: Check SQL syntax
      #   run: |
      #     for file in $(find . -name '*.sql'); do
      #       echo "Checking syntax for $file"
      #       mysql --database=dummy --force < $file || exit 1
      #     done
