name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1

      - name: Check Java Syntax
        run: javac **/*.java

      - name: Lint SQL files
        run: |
          sudo apt-get install -y sqlfluff
          sqlfluff lint **/*.sql
